fix controller endpoint (#74)
Summary:

Monarch is enforcing the following check. This diff is a fix.

ValueError: <class 'torchstore.controller.Controller'> mixes both async and sync endpoints.Synchronous endpoints cannot be mixed with async endpoints because they can cause the asyncio loop to deadlock if they wait.sync: ['get_controller_strategy', 'keys', 'locate_volumes', 'notify_delete', 'notify_put'] async: ['init', 'teardown']

Reviewed By: amirafzali, LucasLLC

Differential Revision: D86155590